// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	projectsList: () => typedError<Project[], AppError>(__TAURI_INVOKE("projects_list")),
	projectsGet: (id: string) => typedError<{
	id: string,
	name: string,
	description: string,
	schemaVersion: number,
	createdAt: number | null,
	updatedAt: number | null,
	ampAssignments: AmpAssignment[],
} | null, AppError>(__TAURI_INVOKE("projects_get", { id })),
	projectsCreate: (name: string, description: string) => typedError<Project, AppError>(__TAURI_INVOKE("projects_create", { name, description })),
	/**
	 *  Full-document replace, matching the old app's PUT-whole-project pattern.
	 *  Bumps `updated_at` regardless of what the caller passed.
	 */
	projectsUpdate: (project: Project) => typedError<Project, AppError>(__TAURI_INVOKE("projects_update", { project })),
	projectsDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("projects_delete", { id })),
	/**
	 *  Adds an amp assignment to a project by model/label alone — `mac` starts
	 *  unset (`None`) and is linked later via live network discovery, not typed
	 *  in manually. If `amp_model_id` references a catalog entry, its channel
	 *  count pre-populates the assignment's channels.
	 */
	projectsAddAmpAssignment: (projectId: string, label: string | null, ampModelId: string | null, firmwareVersion: string | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_add_amp_assignment", { projectId, label, ampModelId, firmwareVersion })),
	projectsRemoveAmpAssignment: (projectId: string, assignmentId: string) => typedError<Project, AppError>(__TAURI_INVOKE("projects_remove_amp_assignment", { projectId, assignmentId })),
	/**
	 *  Changes (or clears) an assignment's amp model, reconciling its channel
	 *  count additively — grows/shrinks `channels`, preserving existing
	 *  per-channel config where indices still exist. Never a destructive wipe.
	 */
	projectsSetAmpModel: (projectId: string, assignmentId: string, ampModelId: string | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_amp_model", { projectId, assignmentId, ampModelId })),
	projectsSetChannelOhms: (projectId: string, assignmentId: string, channelIndex: number, ohms: number | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_ohms", { projectId, assignmentId, channelIndex, ohms })),
	/**
	 *  Sets which physical source feeds a channel's input — Routing tab. There is
	 *  no "no source": a physical input always has one. A `kind` with no `index`
	 *  defaults to physical input 0 of that kind.
	 */
	projectsSetChannelSource: (projectId: string, assignmentId: string, channelIndex: number, kind: SourceKind, index: number | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_source", { projectId, assignmentId, channelIndex, kind, index })),
	/**
	 *  Partial update of one Matrix-tab crosspoint — only touches the fields the
	 *  caller passes (`Some`), matching the other partial-update commands'
	 *  per-field-optional convention. Fails if the crosspoint doesn't exist yet
	 *  (it should always exist by the time the UI can edit it, since
	 *  `reconcile_matrix_size` pre-populates every crosspoint for the model's
	 *  `matrix_input_count`).
	 */
	projectsSetMatrixCrosspoint: (projectId: string, assignmentId: string, channelIndex: number, sourceIndex: number, gainDb: number | null, active: boolean | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_matrix_crosspoint", { projectId, assignmentId, channelIndex, sourceIndex, gainDb, active })),
	/**  Sets a channel's input delay — Input tab. */
	projectsSetChannelDelayIn: (projectId: string, assignmentId: string, channelIndex: number, delayInMs: number | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_delay_in", { projectId, assignmentId, channelIndex, delayInMs })),
	/**  Sets whether a channel's input is muted — Input tab. */
	projectsSetChannelInputMute: (projectId: string, assignmentId: string, channelIndex: number, muted: boolean) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_input_mute", { projectId, assignmentId, channelIndex, muted })),
	/**
	 *  Partial update of a channel's output trim/volume/delay — Output tab. Only
	 *  touches the fields the caller passes (`Some`), matching
	 *  `projects_set_matrix_crosspoint`'s per-field-optional convention.
	 */
	projectsSetChannelOutput: (projectId: string, assignmentId: string, channelIndex: number, trimDb: number | null, volumeDb: number | null, delayOutMs: number | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_output", { projectId, assignmentId, channelIndex, trimDb, volumeDb, delayOutMs })),
	/**
	 *  Partial update of a channel's HP or LP crossover slot (band 0 / band 9 of
	 *  its `input_eq`/`output_eq` chain) — EQ sub-tab. Only touches the fields
	 *  the caller passes (`Some`), matching `projects_set_matrix_crosspoint`'s
	 *  per-field-optional convention.
	 */
	projectsSetCrossoverSlot: (projectId: string, assignmentId: string, channelIndex: number, direction: EqDirection, slot: CrossoverSlotKind, patch: CrossoverSlotPatch) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_crossover_slot", { projectId, assignmentId, channelIndex, direction, slot, patch })),
	/**
	 *  Partial update of one parametric EQ band (bands 1-8 of the `input_eq`/
	 *  `output_eq` chain) — EQ sub-tab. Only touches the fields the caller
	 *  passes (`Some`). Fails if `band_index` is out of range (it should always
	 *  exist by the time the UI can edit it, since `reconcile_eq_bands`
	 *  pre-populates every band for the model's `eq_bands_per_channel`).
	 */
	projectsSetEqBand: (projectId: string, assignmentId: string, channelIndex: number, direction: EqDirection, bandIndex: number, patch: EqBandPatch) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_eq_band", { projectId, assignmentId, channelIndex, direction, bandIndex, patch })),
	/**
	 *  Partial update of a channel's output protection (RMS + Peak limiter
	 *  stages) — Output tab's Limiter sub-tab.
	 */
	projectsSetChannelLimiter: (projectId: string, assignmentId: string, channelIndex: number, patch: LimiterPatch) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_limiter", { projectId, assignmentId, channelIndex, patch })),
	/**
	 *  Partial update of a channel's noise gate — Output tab. The threshold is
	 *  always persisted regardless of firmware; the frontend only shows it as
	 *  user-adjustable when `CvrFirmwareCapability.noise_gate_threshold` is true.
	 */
	projectsSetChannelNoiseGate: (projectId: string, assignmentId: string, channelIndex: number, enabled: boolean | null, thresholdDbu: number | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_noise_gate", { projectId, assignmentId, channelIndex, enabled, thresholdDbu })),
	/**  Toggles a channel's output polarity/phase invert — Output tab. */
	projectsSetChannelPhaseInvert: (projectId: string, assignmentId: string, channelIndex: number, inverted: boolean) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_phase_invert", { projectId, assignmentId, channelIndex, inverted })),
	/**
	 *  Renames a channel's input or output label, overriding the default
	 *  numbered/lettered label — Input/Output tabs. `name: None` clears back to
	 *  the default.
	 */
	projectsSetChannelName: (projectId: string, assignmentId: string, channelIndex: number, direction: EqDirection, name: string | null) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_name", { projectId, assignmentId, channelIndex, direction, name })),
	/**
	 *  Toggles a channel's output mute — Output tab. Mirrors
	 *  `projects_set_channel_input_mute`.
	 */
	projectsSetChannelOutputMute: (projectId: string, assignmentId: string, channelIndex: number, muted: boolean) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_output_mute", { projectId, assignmentId, channelIndex, muted })),
	/**
	 *  Toggles mono-bridging for a channel pair — Output tab. `pair_leader_channel_index`
	 *  must be even and have a following odd-indexed partner in the same
	 *  assignment; the flag itself lives only on the leader (see
	 *  `AmpChannel.output_bridged`'s doc comment).
	 */
	projectsSetOutputBridge: (projectId: string, assignmentId: string, pairLeaderChannelIndex: number, bridged: boolean) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_output_bridge", { projectId, assignmentId, pairLeaderChannelIndex, bridged })),
	/**  Sets a channel's output power/impedance mode — Output tab. */
	projectsSetChannelPowerMode: (projectId: string, assignmentId: string, channelIndex: number, powerMode: PowerMode) => typedError<Project, AppError>(__TAURI_INVOKE("projects_set_channel_power_mode", { projectId, assignmentId, channelIndex, powerMode })),
	/**
	 *  Resolves what can be configured, and within what ranges, for a given amp
	 *  model + firmware version — purely offline, no live device involved.
	 *  Nothing here is persisted independently: it's always recomputed from the
	 *  catalog entry's topology and the (free-text) firmware version string.
	 */
	ampCapabilityResolve: (ampModelId: string, firmwareVersion: string | null) => typedError<AmpCapability_Serialize, AppError>(__TAURI_INVOKE("amp_capability_resolve", { ampModelId, firmwareVersion })),
	ampModelsList: () => typedError<AmpModelCatalogEntry_Serialize[], AppError>(__TAURI_INVOKE("amp_models_list")),
	ampModelsCreate: (brand: string, model: string, channelCount: number, isDante: boolean, protocol: AmpProtocol) => typedError<AmpModelCatalogEntry_Serialize, AppError>(__TAURI_INVOKE("amp_models_create", { brand, model, channelCount, isDante, protocol })),
	/**
	 *  Full-entry replace, mirroring `projects_update`'s pattern. Changing
	 *  `channel_count` here does NOT retroactively touch any Project's
	 *  assignments — reconciliation only happens explicitly via
	 *  `projects_set_amp_model`.
	 */
	ampModelsUpdate: (entry: AmpModelCatalogEntry_Deserialize) => typedError<AmpModelCatalogEntry_Serialize, AppError>(__TAURI_INVOKE("amp_models_update", { entry })),
	/**  Soft-delete — see `AmpModelCatalogEntry.archived` for rationale. */
	ampModelsArchive: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("amp_models_archive", { id })),
	liveControlStart: () => typedError<null, AppError>(__TAURI_INVOKE("live_control_start")),
	/**
	 *  Declares which devices one live consumer needs the heavy polls (heartbeat,
	 *  FC=27, FC=50) for. Devices no consumer has asked for get discovery alone.
	 * 
	 *  `token` identifies one subscription, and `device_ids` replaces that
	 *  token's whole set; an empty list removes the token. The driver polls the
	 *  union of every token's set, so any number of views can subscribe at once
	 *  — Live Control today, project mode once offline/online amp fusion lands —
	 *  without overwriting each other, and two views on the same amp never
	 *  double-poll it. The frontend mints a fresh token per effect run (see
	 *  `useLivePolling`), which keeps this correct even when a subscribe and a
	 *  clear arrive out of order.
	 * 
	 *  Pure state, no wire I/O: the ticks read it on their next pass, so a newly
	 *  subscribed device gets its first heartbeat within ~50ms and its first
	 *  FC=27 within ~200ms. On-demand commands (preset fetch, refresh, writes and
	 *  the post-bridge-write refetch) do not depend on it.
	 */
	liveControlSetPollSubscription: (token: string, deviceIds: string[]) => typedError<null, AppError>(__TAURI_INVOKE("live_control_set_poll_subscription", { token, deviceIds })),
	liveControlStop: () => typedError<null, AppError>(__TAURI_INVOKE("live_control_stop")),
	liveControlListDevices: () => typedError<DiscoveredDevice[], AppError>(__TAURI_INVOKE("live_control_list_devices")),
	liveControlGetTelemetry: () => typedError<DeviceTelemetry[], AppError>(__TAURI_INVOKE("live_control_get_telemetry")),
	liveControlGetChannelConfig: () => typedError<DeviceChannelConfig[], AppError>(__TAURI_INVOKE("live_control_get_channel_config")),
	/**
	 *  On-demand counterpart to the background ~200ms FC=27 poll (see
	 *  `driver.rs`'s `config_poll_tick`): sends one SYNC_DATA request through the
	 *  driver's request registry with an `External` sink and awaits its result
	 *  directly, instead of waiting for the next passive poll tick to pick it up.
	 *  Still updates `LiveDeviceState.channel_config` and emits
	 *  `live_channel_config:updated` exactly like the background poll does (via
	 *  the shared `parse_and_store_sync_data`), so callers that only listen for
	 *  the event rather than this command's return value stay in sync too.
	 */
	liveControlRefreshNow: (deviceId: string) => typedError<DeviceChannelConfig, AppError>(__TAURI_INVOKE("live_control_refresh_now", { deviceId })),
	/**
	 *  Fetches the full preset slot-name list (FC=59 mode=0) and the currently
	 *  active preset's name (mode=4) as one command — deliberately not two
	 *  independently-callable commands, since both share the same FC=59 request
	 *  registry key and must not overlap (see `send_request_with_retry`'s doc). The
	 *  mode=4 request is only sent after the mode=0 oneshot has resolved. Stores
	 *  the result and emits `live_presets:updated`, same pattern as
	 *  `live_control_refresh_now`/`parse_and_store_sync_data`.
	 */
	liveControlFetchPresets: (deviceId: string) => typedError<DevicePresets, AppError>(__TAURI_INVOKE("live_control_fetch_presets", { deviceId })),
	/**
	 *  Snapshot getter mirroring `live_control_get_channel_config` — returns
	 *  whatever `live_control_fetch_presets` last stored, no wire I/O.
	 */
	liveControlGetPresets: () => typedError<DevicePresets[], AppError>(__TAURI_INVOKE("live_control_get_presets")),
	/**
	 *  FC=59 mode=2 recall, same convention as every other write in this app
	 *  (see `write.rs`'s module doc): returns once the device has ACKed the
	 *  packet, which confirms delivery only. The device's new active preset
	 *  still shows up on the next manual `live_control_fetch_presets` call, not
	 *  pushed automatically here.
	 */
	liveControlRecallPreset: (deviceId: string, slotIndex: number) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_recall_preset", { deviceId, slotIndex })),
	/**
	 *  FC=59 mode=1 store — writes the device's *current* DSP state into
	 *  `slot_index` under `name`. Note the asymmetry with recall: the wire
	 *  protocol carries only the name, never parameter data (see `preset.rs`),
	 *  so this saves whatever the amp is doing right now rather than pushing
	 *  anything from the app.
	 * 
	 *  Rejects a name the device cannot round-trip: `decode_name_field` reads
	 *  slot names back as a null-terminated ASCII field, so an embedded NUL
	 *  would silently truncate the stored name and non-ASCII bytes would come
	 *  back mangled. Empty names are rejected too — the list parser has no way
	 *  to distinguish one from an unused slot.
	 */
	liveControlStorePreset: (deviceId: string, slotIndex: number, name: string) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_store_preset", { deviceId, slotIndex, name })),
	/**
	 *  Snapshot getter for FC=50 bridge state — no wire I/O, just whatever the
	 *  driver's bridge poll tick last stored. Mirrors
	 *  `live_control_get_presets`; the continuous push side is the
	 *  `live_bridge:updated` event.
	 */
	liveControlGetBridge: () => typedError<DeviceBridge[], AppError>(__TAURI_INVOKE("live_control_get_bridge")),
	/**
	 *  Reads every bridge pair now and waits for the answers, instead of waiting
	 *  for the driver's own bridge tick to come round to them — the FC=50
	 *  counterpart to `live_control_fetch_presets`. Used when an amp's editor
	 *  opens: a project amp's fingerprint cannot be completed until every pair
	 *  has been reported (see `data/fingerprint.rs`), so the editor would
	 *  otherwise sit locked until the tick catches up.
	 * 
	 *  The pairs go out one after another — `RequestRegistry` keys pending
	 *  requests by `(ip, function_code)`, so two FC=50 requests cannot be in
	 *  flight at once. Each answer is stored through the same `LiveEventSink`
	 *  the driver would have used, so `live_bridge:updated` fires exactly as it
	 *  does for a polled reply.
	 */
	liveControlFetchBridge: (deviceId: string) => typedError<DeviceBridge, AppError>(__TAURI_INVOKE("live_control_fetch_bridge", { deviceId })),
	/**
	 *  FC=12 ROUTING. `gain_db`/`active` are both optional; whichever is omitted
	 *  is filled from the crosspoint's current state, since the wire packet has
	 *  no partial form (see `current_channel`).
	 */
	liveControlSetMatrixCrosspoint: (deviceId: string, channelIndex: number, sourceIndex: number, gainDb: number | null, active: boolean | null) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_matrix_crosspoint", { deviceId, channelIndex, sourceIndex, gainDb, active })),
	/**
	 *  FC=69 NOISE_GATE. `threshold_dbu` is only carried on 1.1.9+ — on 1.1.8 the
	 *  wire body is the enable flag alone, matching
	 *  `CvrFirmwareCapability.noise_gate_threshold`.
	 */
	liveControlSetChannelNoiseGate: (deviceId: string, channelIndex: number, enabled: boolean, thresholdDbu: number | null) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_noise_gate", { deviceId, channelIndex, enabled, thresholdDbu })),
	/**
	 *  FC=55 RMS_LIMITER / FC=54 PEAK_LIMITER. Takes the same `LimiterPatch` the
	 *  project-mode command does, and sends one packet per stage the patch
	 *  actually touches — a patch that only changes an RMS field leaves the peak
	 *  stage alone rather than rewriting it.
	 * 
	 *  Each stage is a whole-record write, so the fields the patch omits come
	 *  from the current snapshot (see `current_channel`).
	 */
	liveControlSetChannelLimiter: (deviceId: string, channelIndex: number, patch: LimiterPatch) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_limiter", { deviceId, channelIndex, patch })),
	/**
	 *  FC=77 SPEAKER_NAME. `direction` picks which side of the channel is
	 *  renamed — the only wire difference is `in_out_flag`.
	 * 
	 *  Clearing a name (`None`) writes an all-zero field, which is how the read
	 *  side already decodes "unnamed" (`decode_name_field` stops at the first
	 *  NUL). Same ASCII/length rules as the preset store, against the channel
	 *  field's narrower 16-byte width.
	 */
	liveControlSetChannelName: (deviceId: string, channelIndex: number, direction: EqDirection, name: string | null) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_name", { deviceId, channelIndex, direction, name })),
	/**
	 *  FC=11 SOURCE_SELECT, plus FC=79 ANALOG_MATRIX_INPUT for an Analog pick.
	 * 
	 *  FC=11 carries only the source *kind*. Which physical analog input feeds
	 *  the channel is a separate write — the vendor's `AnalogType` property
	 *  (`Channels.cs`) and the reference's `analogType` action both send FC=79
	 *  with the 0-based input index. Sending FC=11 alone made "Analog 2" on a
	 *  channel already on analog a no-op on the device, even though the packet
	 *  was acknowledged. `index` is only meaningful for Analog; Dante/AES3 are
	 *  hard-wired 1:1 to their channel, so it is ignored for those kinds.
	 * 
	 *  `SourceKind::Backup` is rejected: it is a readback state (raw code >= 3,
	 *  see `channel_config_v118::source`), not something FC=11 selects — the
	 *  reference's own comment notes backup is driven by the priority/auto-source
	 *  controls (FC=80), which is Tier B.
	 */
	liveControlSetChannelSource: (deviceId: string, channelIndex: number, kind: SourceKind, index: number | null) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_source", { deviceId, channelIndex, kind, index })),
	/**
	 *  FC=50 BRIDGE. `channel_index` is the bridged pair's **leader channel**,
	 *  keeping this command's signature identical to the project-mode
	 *  `projects_set_output_bridge` so `ConfigureActions` needs no per-source
	 *  branching.
	 * 
	 *  The wire, however, addresses **pairs** (0 = A/B, 1 = C/D), so the
	 *  conversion happens right here at the boundary. Passing the leader channel
	 *  through unconverted is what made bridging work for A/B and silently do
	 *  nothing for C/D — channel 2 became `chx=2`, which the device does not
	 *  recognise as a pair.
	 */
	liveControlSetOutputBridge: (deviceId: string, channelIndex: number, bridged: boolean) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_output_bridge", { deviceId, channelIndex, bridged })),
	/**
	 *  Returns once the device has ACKed the write at the transport level (see
	 *  `write.rs`'s `send_control`), or errors if it never does — delivery is
	 *  confirmed, but not that the device applied the value. The next FC=27 poll
	 *  (already running for every discovered device, see `driver.rs`) picks up
	 *  the real new state and pushes it to the frontend via the existing
	 *  `live_channel_config:updated` event — no optimistic update here.
	 */
	liveControlSetOutputMute: (deviceId: string, channelIndex: number, muted: boolean) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_output_mute", { deviceId, channelIndex, muted })),
	/**
	 *  Partial update of a channel's output trim/volume/delay — mirrors
	 *  `projects_set_channel_output`'s per-field-optional convention, but unlike
	 *  that single-struct-mutation command, each populated field here is its own
	 *  wire write (different FC/`in_out_flag` per field, see `write_v118.rs`) —
	 *  up to three UDP sends per call, each awaited to its ACK before the next
	 *  goes out (writes are stop-and-wait per device; see `WriteRegistry`), so a
	 *  failure on any field surfaces instead of being masked by the others.
	 */
	liveControlSetChannelOutput: (deviceId: string, channelIndex: number, trimDb: number | null, volumeDb: number | null, delayOutMs: number | null) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_output", { deviceId, channelIndex, trimDb, volumeDb, delayOutMs })),
	liveControlSetChannelDelayIn: (deviceId: string, channelIndex: number, delayInMs: number | null) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_delay_in", { deviceId, channelIndex, delayInMs })),
	liveControlSetChannelInputMute: (deviceId: string, channelIndex: number, muted: boolean) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_input_mute", { deviceId, channelIndex, muted })),
	liveControlSetChannelPhaseInvert: (deviceId: string, channelIndex: number, inverted: boolean) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_phase_invert", { deviceId, channelIndex, inverted })),
	liveControlSetChannelPowerMode: (deviceId: string, channelIndex: number, powerMode: PowerMode) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_channel_power_mode", { deviceId, channelIndex, powerMode })),
	/**
	 *  Partial update of one parametric EQ band (1-8) — mirrors
	 *  `projects_set_eq_band`'s shape (`EqBandPatch`, only non-`None` fields
	 *  applied), but `filter_type`/`active` share one wire byte (FC=30) on this
	 *  protocol, so touching either one requires merging in the *other's*
	 *  current value first (see `current_eq_band`) rather than writing a
	 *  stale/default byte for whichever field wasn't part of this patch.
	 *  `freq_hz`/`gain_db`/`q` are independent FCs (32/31/34) and each sends its
	 *  own packet when present in the patch — up to 4 UDP sends per call.
	 */
	liveControlSetEqBand: (deviceId: string, channelIndex: number, direction: EqDirection, bandIndex: number, patch: EqBandPatch) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_eq_band", { deviceId, channelIndex, direction, bandIndex, patch })),
	/**
	 *  Partial update of the HP or LP crossover slot — same `filter_type`/
	 *  `active` merge requirement as `live_control_set_eq_band` (see its doc
	 *  comment), plus a device-required follow-up: any FILTER_TYPE/FILTER_FREQ
	 *  write to a crossover slot only takes effect once
	 *  `write::CROSSOVER_COMMIT_PACKET` is sent afterward (reverse-engineered by
	 *  the reference implementation from real packet captures — see that
	 *  constant's doc comment). Sent once per call, after whichever field(s)
	 *  were actually written, not once per field.
	 */
	liveControlSetCrossoverSlot: (deviceId: string, channelIndex: number, direction: EqDirection, slot: CrossoverSlotKind, patch: CrossoverSlotPatch) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_crossover_slot", { deviceId, channelIndex, direction, slot, patch })),
	/**
	 *  Resolves which catalog model a live device (identified by `mac`) should
	 *  be configured as. An existing manual pick (`auto_matched: false`) always
	 *  wins and is returned as-is, never re-matched. Otherwise runs
	 *  `match_catalog_model`; on a confident match, upserts an `auto_matched:
	 *  true` link (safe to silently refresh on every reconnect) and returns it;
	 *  on no confident match, returns `None` rather than guessing.
	 */
	deviceModelLinkAutoMatch: (mac: string, firmwareVersion: string, digitalInputChannels: number, outputChannels: number) => typedError<{
	id: string,
	brand: string,
	model: string,
	channelCount: number,
	/**
	 *  Authoritative Dante-variant flag — replaces string-matching on the
	 *  model name (e.g. a trailing "D") in the frontend.
	 */
	isDante: boolean,
	protocol: AmpProtocol,
	topology: AmpDspTopology_Serialize,
	notes: string | null,
	origin: EntryOrigin,
	/**
	 *  Soft-delete flag — archived entries stay resolvable for existing
	 *  Project references but are hidden from pickers for new assignments.
	 */
	archived: boolean,
	createdAt: number | null,
	updatedAt: number | null,
} | null, AppError>(__TAURI_INVOKE("device_model_link_auto_match", { mac, firmwareVersion, digitalInputChannels, outputChannels })),
	/**
	 *  Explicit manual pick/clear — always `auto_matched: false`, so a later
	 *  `device_model_link_auto_match` call never silently overrides it.
	 *  `amp_model_id: None` clears any existing link for this `mac`.
	 */
	deviceModelLinkSet: (mac: string, ampModelId: string | null) => typedError<{
	mac: string,
	ampModelId: string,
	/**
	 *  `true` when produced by `match_catalog_model`, `false` when the user
	 *  explicitly picked/overrode it — an auto-match is safe to silently
	 *  re-run and refresh on every reconnect, a manual pick never is.
	 */
	autoMatched: boolean,
	updatedAt: number | null,
} | null, AppError>(__TAURI_INVOKE("device_model_link_set", { mac, ampModelId })),
	deviceModelLinkGetAll: () => typedError<DeviceModelLink[], AppError>(__TAURI_INVOKE("device_model_link_get_all")),
	/**
	 *  Read-only: builds the fingerprint of one planned amp from the stored
	 *  project. No save, no event — see `data/fingerprint.rs` for what is hashed.
	 */
	fingerprintProjectAmp: (projectId: string, assignmentId: string) => typedError<AmpFingerprint, AppError>(__TAURI_INVOKE("fingerprint_project_amp", { projectId, assignmentId })),
	/**  Every amp in a project, in assignment order. */
	fingerprintProject: (projectId: string) => typedError<AmpFingerprint[], AppError>(__TAURI_INVOKE("fingerprint_project", { projectId })),
	/**
	 *  Read-only: fingerprint of a live device from its latest FC=27 snapshot
	 *  (plus FC=50 bridge state). Fails when no snapshot has arrived yet — the
	 *  device must be polled first.
	 */
	fingerprintLiveDevice: (deviceId: string) => typedError<AmpFingerprint, AppError>(__TAURI_INVOKE("fingerprint_live_device", { deviceId })),
	/**
	 *  Every discovered device that has an FC=27 snapshot, ordered by device id.
	 *  Devices never polled are skipped rather than failing the whole call.
	 */
	fingerprintLiveDevices: () => typedError<AmpFingerprint[], AppError>(__TAURI_INVOKE("fingerprint_live_devices")),
	/**
	 *  Read-only: can `device_id` be linked to this project amp? See
	 *  `data/amp_link.rs` for the checks.
	 */
	projectsValidateAmpLink: (projectId: string, assignmentId: string, deviceId: string) => typedError<AmpLinkValidation, AppError>(__TAURI_INVOKE("projects_validate_amp_link", { projectId, assignmentId, deviceId })),
	/**
	 *  Links a live device to a project amp by writing its MAC. Re-validates
	 *  under the project lock and refuses on any failing check — the frontend's
	 *  earlier validation is never trusted. Config is not touched; matching
	 *  offline and online settings happens in the editor.
	 */
	projectsLinkAmp: (projectId: string, assignmentId: string, deviceId: string) => typedError<Project, AppError>(__TAURI_INVOKE("projects_link_amp", { projectId, assignmentId, deviceId })),
	/**  Clears a project amp's linked MAC. Planned config is left untouched. */
	projectsUnlinkAmp: (projectId: string, assignmentId: string) => typedError<Project, AppError>(__TAURI_INVOKE("projects_unlink_amp", { projectId, assignmentId })),
	/**
	 *  Read-only: whether this project amp is editable right now, with both
	 *  fingerprints and the field-by-field comparison when it's locked. See
	 *  `data/edit_lock.rs`.
	 */
	projectsAmpEditLock: (projectId: string, assignmentId: string) => typedError<AmpEditLock, AppError>(__TAURI_INVOKE("projects_amp_edit_lock", { projectId, assignmentId })),
	/**
	 *  Copies the linked network amp's settings into this project amp (offline ←
	 *  online). All or nothing: the mirrored candidate is re-fingerprinted and
	 *  only saved when its amp hash equals the online amp's; otherwise nothing is
	 *  written and the still-differing rows come back. See `data/amp_merge.rs`
	 *  for what is and isn't copied.
	 */
	projectsMergeAmpFromLive: (projectId: string, assignmentId: string) => typedError<AmpMergeResult, AppError>(__TAURI_INVOKE("projects_merge_amp_from_live", { projectId, assignmentId })),
	/**
	 *  FC=17 ROTARY_LOCK — locks/unlocks the amp's front-panel knobs. Does not
	 *  affect what this app may edit. No explicit refetch: the new state comes
	 *  back through the next FC=27 poll (`rotary_locked`).
	 */
	liveControlSetRotaryLock: (deviceId: string, locked: boolean) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_rotary_lock", { deviceId, locked })),
	/**
	 *  FC=15 STANDBY — puts the amp into standby or brings it back out. Amp-wide,
	 *  not per channel. No explicit refetch: the new state comes back through the
	 *  next FC=27 poll (`standby`), same as the front-panel lock.
	 * 
	 *  Deliberately does not check `standby_locked` (FC=27 byte 32 == 2)
	 *  before sending: the frontend disables the control in that case, and the
	 *  authority on whether the amp will accept it is the amp, not a cached poll.
	 */
	liveControlSetStandby: (deviceId: string, standby: boolean) => typedError<LiveWriteAck, AppError>(__TAURI_INVOKE("live_control_set_standby", { deviceId, standby })),
};

/* Types */
/**
 *  One assigned amp "slot" within a Project. `id` is independent of `mac` so
 *  a slot's configuration survives a physical unit swap. `mac` starts unset
 *  at creation time — a slot is planned by model/label alone; linking it to
 *  a physical unit's MAC happens later via live network discovery, not by
 *  manual entry.
 */
export type AmpAssignment = {
	id: string,
	mac: string | null,
	label: string | null,
	ampModelId: string | null,
	/**
	 *  Firmware version this slot is being planned for (e.g. "1.1.8",
	 *  "1.1.9") — declared by the user at planning time, not detected, since
	 *  offline planning has no live device to sniff it from. Free text
	 *  (mirrors `DiscoveredDevice.firmware_family`) rather than a closed
	 *  enum, since it's protocol-specific and protocols are pluggable.
	 */
	firmwareVersion?: string | null,
	channels: AmpChannel[],
	/**
	 *  The amp's user-set name (FC=60 `CUSTOMER_NAME_MODIFY`, read back via FC=0
	 *  BASIC_INFO). Not yet editable here.
	 */
	deviceName?: string | null,
};

/**
 *  Combined, resolved answer to "what can be configured, and within what
 *  ranges" for one (amp model, firmware version) pair. Never persisted
 *  independently — always recomputed by `resolve()` from an
 *  `AmpModelCatalogEntry` and an `AmpAssignment.firmware_version`.
 */
export type AmpCapability = AmpCapability_Serialize | AmpCapability_Deserialize;

/**
 *  Combined, resolved answer to "what can be configured, and within what
 *  ranges" for one (amp model, firmware version) pair. Never persisted
 *  independently — always recomputed by `resolve()` from an
 *  `AmpModelCatalogEntry` and an `AmpAssignment.firmware_version`.
 */
export type AmpCapability_Deserialize = {
	topology: AmpDspTopology_Deserialize,
	firmware: CvrFirmwareCapability,
	paramRanges: AmpParamRanges,
	/**
	 *  Which `EqFilterType`s expose gain/Q — EQ tab's band editor. See
	 *  `eq_filter_capabilities()`.
	 */
	eqFilterCapabilities: EqFilterCapabilityEntry[],
};

/**
 *  Combined, resolved answer to "what can be configured, and within what
 *  ranges" for one (amp model, firmware version) pair. Never persisted
 *  independently — always recomputed by `resolve()` from an
 *  `AmpModelCatalogEntry` and an `AmpAssignment.firmware_version`.
 */
export type AmpCapability_Serialize = {
	topology: AmpDspTopology_Serialize,
	firmware: CvrFirmwareCapability,
	paramRanges: AmpParamRanges,
	/**
	 *  Which `EqFilterType`s expose gain/Q — EQ tab's band editor. See
	 *  `eq_filter_capabilities()`.
	 */
	eqFilterCapabilities: EqFilterCapabilityEntry[],
};

/**
 *  Per-channel config on an amp assignment. `ohms` is the channel's load
 *  impedance, used by the Limiter; the amp reports its own as `load_data`.
 */
export type AmpChannel = {
	channelIndex: number,
	ohms: number | null,
	/**
	 *  Which physical source feeds this channel's input — Routing tab.
	 *  Always set: a physical input always has a source. New channels
	 *  default to Analog N (1:1); older files are backfilled on load (see
	 *  `CURRENT_PROJECT_SCHEMA_VERSION`).
	 */
	source: ChannelSource,
	/**
	 *  One crosspoint per possible matrix source (0..matrix_input_count) —
	 *  Matrix tab. Grown/shrunk alongside `channels` whenever the assigned
	 *  model (hence its topology) changes; see `reconcile_matrix_size`.
	 */
	matrixCrosspoints?: MatrixCrosspoint[],
	/**  Input delay, ranged by `AmpParamRanges.delay_in_ms` — Input tab. */
	delayInMs?: number | null,
	/**  Whether this channel's input is muted — Input tab. */
	inputMuted?: boolean,
	/**  Output trim, ranged by `AmpParamRanges.output_trim_db` — Output tab. */
	outputTrimDb?: number | null,
	/**  Output volume, ranged by `AmpParamRanges.output_volume_db` — Output tab. */
	outputVolumeDb?: number | null,
	/**  Output delay, ranged by `AmpParamRanges.delay_out_ms` — Output tab. */
	delayOutMs?: number | null,
	/**  Input EQ tab's 10-band chain (pre-matrix). */
	inputEq?: ChannelEq,
	/**  Output EQ tab's 10-band chain (post-matrix), independent of `input_eq`. */
	outputEq?: ChannelEq,
	/**
	 *  Output protection — RMS + Peak limiter stages, Output tab's Limiter
	 *  sub-tab.
	 */
	limiter?: Limiter,
	/**
	 *  Whether the output noise gate is engaged — Output tab. Threshold is
	 *  only user-adjustable in the UI when
	 *  `CvrFirmwareCapability.noise_gate_threshold` is true, but is always
	 *  persisted regardless of firmware.
	 */
	noiseGateEnabled?: boolean,
	/**
	 *  Noise gate threshold in dBu, ranged by
	 *  `AmpParamRanges.noise_gate_threshold_dbu` — Output tab.
	 */
	noiseGateThresholdDbu?: number | null,
	/**  Output polarity/phase invert — Output tab. */
	outputPhaseInverted?: boolean,
	/**
	 *  User-assigned label for this channel's input side, overriding the
	 *  default "In{n}" label. `None` uses the default. Max length ranged by
	 *  `AmpParamRanges.channel_name_max_length`.
	 */
	inputName?: string | null,
	/**
	 *  User-assigned label for this channel's output side, overriding the
	 *  default "Out{letter}" label. `None` uses the default.
	 */
	outputName?: string | null,
	/**
	 *  Whether this channel's output is muted — Output tab. Mirrors
	 *  `input_muted`.
	 */
	outputMuted?: boolean,
	/**
	 *  Whether this channel is mono-bridged with the next channel (fixed
	 *  adjacent pairing: `floor(channel_index / 2)` — (0,1), (2,3), …) —
	 *  Output tab. **Only meaningful on an even-indexed (pair-leader)
	 *  channel with a following odd-indexed partner**; ignored/never read
	 *  on odd (follower) channels or on a leader with no partner (e.g. the
	 *  trailing channel of an odd-count assignment). Ported from the old
	 *  app's per-pair `BridgeReadback`, adapted to a plain persisted field
	 *  since this is offline planning, not a live device readback.
	 */
	outputBridged?: boolean,
	/**
	 *  Output power/impedance mode — Output tab. Ranged by
	 *  `AmpDspTopology.power_modes` (which modes the assigned model actually
	 *  offers), though CVR currently offers all three unconditionally.
	 */
	powerMode?: PowerMode,
	/**  FIR filter bypass. Read back, not yet editable here. */
	firBypassed?: boolean,
	/**  Per-source trim/delay. Read back, not yet editable here. */
	sourceTrims?: SourceTrims,
	/**  Backup source switching. Read back, not yet editable here. */
	backupPriority?: BackupPriority,
};

/**
 *  One channel's (or the amp's) operating state, decoded from the vendor's
 *  `Jiqizhuangtai` enum. See `channel_state_v118.rs` for the raw-value table
 *  and the two places the vendor's own identifiers and UI labels disagree.
 * 
 *  `Unknown` is a plain variant rather than `Unknown(u32)`: a tagged enum
 *  makes an awkward TypeScript shape, and the raw values stay available on
 *  `Telemetry.output_states`/`input_states`/`machine_mode` for wire debugging,
 *  so carrying the byte twice buys nothing.
 */
export type AmpChannelState = "offline" | "normal" | "standby" | "fault" | "open" | "overload" | "clip" | "dcp" | "powerError" | "run" | "temp" | "limit" | "sleep" | "unknown";

/**
 *  Per-model DSP-capability schema — channel/IO topology, EQ structure, and
 *  electrical rating for a catalog entry. Populated at seed time for builtin
 *  CVR models (see `capability::cvr::builtin_topology`); defaults to zeroed/
 *  empty for user-defined models until the user (or a future datasheet
 *  import) fills it in. Combined with a firmware-derived capability delta by
 *  `capability::resolve()` to answer "what can be configured" for a given
 *  (model, firmware) pair — see `AmpCapability`.
 */
export type AmpDspTopology = AmpDspTopology_Serialize | AmpDspTopology_Deserialize;

/**
 *  Per-model DSP-capability schema — channel/IO topology, EQ structure, and
 *  electrical rating for a catalog entry. Populated at seed time for builtin
 *  CVR models (see `capability::cvr::builtin_topology`); defaults to zeroed/
 *  empty for user-defined models until the user (or a future datasheet
 *  import) fills it in. Combined with a firmware-derived capability delta by
 *  `capability::resolve()` to answer "what can be configured" for a given
 *  (model, firmware) pair — see `AmpCapability`.
 */
export type AmpDspTopology_Deserialize = {
	matrixInputCount?: number,
	matrixOutputCount?: number,
	eqBandsPerChannel?: number,
	sourceCounts?: SourceChannelCount[],
	powerModes?: PowerMode[],
	/**  `None` for models with no known electrical datasheet (e.g. user-defined). */
	ratedRmsVoltage?: number | null,
};

/**
 *  Per-model DSP-capability schema — channel/IO topology, EQ structure, and
 *  electrical rating for a catalog entry. Populated at seed time for builtin
 *  CVR models (see `capability::cvr::builtin_topology`); defaults to zeroed/
 *  empty for user-defined models until the user (or a future datasheet
 *  import) fills it in. Combined with a firmware-derived capability delta by
 *  `capability::resolve()` to answer "what can be configured" for a given
 *  (model, firmware) pair — see `AmpCapability`.
 */
export type AmpDspTopology_Serialize = {
	matrixInputCount: number,
	matrixOutputCount: number,
	eqBandsPerChannel: number,
	sourceCounts: SourceChannelCount[],
	powerModes: PowerMode[],
	/**  `None` for models with no known electrical datasheet (e.g. user-defined). */
	ratedRmsVoltage: number | null,
};

export type AmpEditLock = {
	state: AmpEditLockState,
	locked: boolean,
	/**  The linked network amp, when it is currently discovered. */
	deviceId: string | null,
	/**
	 *  The amp's front-panel knob lock from its latest FC=27 snapshot.
	 *  Informational only — it never affects `locked`.
	 */
	rotaryLocked: boolean | null,
	/**
	 *  The amp's standby state from the same snapshot, and whether it is
	 *  refusing standby writes. Carried here for exactly the reason
	 *  `rotary_locked` is: these are amp-level controls a project amp's
	 *  configure view offers whenever its linked amp is online, and this lock
	 *  is that view's only channel to the live snapshot. Informational only —
	 *  neither ever affects `locked`.
	 */
	standby: boolean | null,
	standbyLocked: boolean | null,
	project: AmpFingerprint | null,
	live: AmpFingerprint | null,
	rows: FingerprintRow[],
	/**  Why a fingerprint couldn't be computed, prefixed with its side. */
	unreadable: string[],
};

export type AmpEditLockState = 
/**  No MAC on the assignment — editable. */
"unlinked" | 
/**  Linked, but the network amp isn't discovered or is offline — editable. */
"offline" | 
/**  Online, but no FC=27 settings snapshot has arrived yet — locked. */
"checking" | 
/**  Amp hashes are equal — editable. */
"matches" | 
/**  Amp hashes differ — locked. */
"mismatch" | 
/**  A fingerprint couldn't be fully computed — locked. */
"unreadable";

export type AmpFingerprint = {
	fingerprintVersion: number,
	origin: FingerprintOrigin,
	identity: AmpIdentity,
	settings: AmpSettingsCanonical,
	/**  Shown, never hashed. Always empty for a project amp. */
	status: AmpStatus,
	/**  `None` whenever `missing` is non-empty. */
	ampHash: string | null,
	channels: ChannelFingerprint[],
	/**
	 *  One entry per bridgeable pair (A/B, C/D, …); a trailing unpaired
	 *  channel has none. `None` = not reported yet (also listed in `missing`).
	 */
	bridgedPairs: (boolean | null)[],
	/**  Human-readable reasons a hash could not be computed. */
	missing: string[],
};

export type AmpIdentity = {
	/**  Catalog model name, e.g. "DSP-2004" — the hashed identity. */
	model: string | null,
	/**  Informational only; not hashed. */
	ampModelId: string | null,
	channelCount: number,
	/**  Protocol firmware bucket, e.g. "1.1.8"/"1.1.9" for CVR. */
	firmwareFamily: string | null,
};

export type AmpLinkCheck = {
	kind: AmpLinkCheckKind,
	passed: boolean,
	/**  User-facing explanation, shown next to the check in the Link Amp modal. */
	detail: string,
};

export type AmpLinkCheckKind = "deviceOnline" | "modelDetected" | "modelMatches" | "firmwareMatches" | "notLinkedElsewhere";

/**
 *  Whether a live device may be linked to a planned project amp. Every check
 *  is always present (so the UI can list them); `compatible` only when all
 *  pass. All checks are hard blocks — there is no "link anyway".
 */
export type AmpLinkValidation = {
	compatible: boolean,
	detectedModelId: string | null,
	checks: AmpLinkCheck[],
};

/**
 *  Outcome of `projects_merge_amp_from_live`. Flat rather than a tagged enum,
 *  like `FingerprintOrigin`: `merged` says which fields are set.
 */
export type AmpMergeResult = {
	merged: boolean,
	/**  The saved project; `Some` only when `merged`. */
	project: Project | null,
	/**  The amp hash both sides now share; `Some` only when `merged`. */
	ampHash: string | null,
	/**
	 *  Candidate-vs-online rows when the hashes still differed and nothing was
	 *  saved; empty when `merged`.
	 */
	remaining: FingerprintRow[],
};

/**
 *  A reusable, project-independent amp hardware model. Referenced by `AmpAssignment.amp_model_id` to pre-populate
 *  an assignment's channel count during offline planning.
 */
export type AmpModelCatalogEntry = AmpModelCatalogEntry_Serialize | AmpModelCatalogEntry_Deserialize;

/**
 *  A reusable, project-independent amp hardware model. Referenced by `AmpAssignment.amp_model_id` to pre-populate
 *  an assignment's channel count during offline planning.
 */
export type AmpModelCatalogEntry_Deserialize = {
	id: string,
	brand: string,
	model: string,
	channelCount: number,
	/**
	 *  Authoritative Dante-variant flag — replaces string-matching on the
	 *  model name (e.g. a trailing "D") in the frontend.
	 */
	isDante?: boolean,
	protocol?: AmpProtocol,
	topology?: AmpDspTopology_Deserialize,
	notes: string | null,
	origin: EntryOrigin,
	/**
	 *  Soft-delete flag — archived entries stay resolvable for existing
	 *  Project references but are hidden from pickers for new assignments.
	 */
	archived: boolean,
	createdAt: number | null,
	updatedAt: number | null,
};

/**
 *  A reusable, project-independent amp hardware model. Referenced by `AmpAssignment.amp_model_id` to pre-populate
 *  an assignment's channel count during offline planning.
 */
export type AmpModelCatalogEntry_Serialize = {
	id: string,
	brand: string,
	model: string,
	channelCount: number,
	/**
	 *  Authoritative Dante-variant flag — replaces string-matching on the
	 *  model name (e.g. a trailing "D") in the frontend.
	 */
	isDante: boolean,
	protocol: AmpProtocol,
	topology: AmpDspTopology_Serialize,
	notes: string | null,
	origin: EntryOrigin,
	/**
	 *  Soft-delete flag — archived entries stay resolvable for existing
	 *  Project references but are hidden from pickers for new assignments.
	 */
	archived: boolean,
	createdAt: number | null,
	updatedAt: number | null,
};

/**
 *  Global CVR DSP parameter ranges/units — ported 1:1 from the old app's
 *  `lib/constants.ts`.
 */
export type AmpParamRanges = {
	matrixGainDb: ParamRange,
	outputTrimDb: ParamRange,
	outputVolumeDb: ParamRange,
	delayInMs: ParamRange,
	delayOutMs: ParamRange,
	crossoverFreqHz: ParamRange,
	eqBandGainDb: ParamRange,
	eqBandQ: ParamRange,
	presetSlots: ParamRange,
	rmsLimiterThresholdVrms: ParamRange,
	rmsLimiterAttackMs: ParamRange,
	rmsLimiterReleaseMultiplier: ParamRange,
	peakLimiterThresholdVp: ParamRange,
	peakLimiterHoldMs: ParamRange,
	peakLimiterReleaseMs: ParamRange,
	noiseGateThresholdDbu: ParamRange,
	/**
	 *  Max byte length for `AmpChannel.input_name`/`output_name` — a plain
	 *  scalar, not a `ParamRange`, since it's a single bound, not a min/max.
	 */
	channelNameMaxLength: number,
};

/**
 *  Identifies which `AmpDriver` controls a catalog model — a brand-protocol-
 *  family concept, not a firmware version (firmware is a runtime property of
 *  a physical unit, detected at discovery time, not a fixed catalog attribute).
 */
export type AmpProtocol = "cvrUdp";

/**  Amp-wide settings beyond identity. */
export type AmpSettingsCanonical = {
	/**
	 *  The amp's user-set name (written with FC=60, read back via FC=0
	 *  BASIC_INFO). Trimmed; empty when unset.
	 */
	deviceName: string,
};

/**
 *  Operational state read from the amp — shown next to the comparison, never
 *  hashed. Always empty for a project amp.
 */
export type AmpStatus = {
	standby: boolean | null,
	/**
	 *  Whether the amp is refusing standby writes — folded into the `Standby`
	 *  status row's text rather than given a row of its own, since it is
	 *  `false` on every amp that isn't in this unusual state.
	 */
	standbyLocked: boolean | null,
	presetName: string | null,
	rotaryLocked: boolean | null,
};

export type AppError = {
	message: string,
};

/**
 *  Backup source switching for one channel (vendor `StruPriority`). `first`/
 *  `second` are the raw source codes as stored on the amp — which kind a code
 *  names depends on the model's source set, so they are not mapped here.
 */
export type BackupPriority = {
	enabled: boolean,
	first: number,
	second: number,
	thresholdDb: number,
};

/**  The per-channel fields `ampHash` covers beyond the speaker hash. */
export type ChannelAmpCanonical = {
	inputEq: EqCanonical,
	/**
	 *  `None` only for a live channel whose source byte is unreadable (also
	 *  listed in `missing`); a project channel always has a source.
	 */
	source: ChannelSource | null,
	/**  Only the model's matrix inputs (`0..matrix_input_count`). */
	matrixCrosspoints: CrosspointCanonical[],
	delayInMs: number | null,
	outputTrimDb: number | null,
	outputVolumeDb: number | null,
	noiseGateEnabled: boolean,
	/**  Trimmed; empty when unnamed or still the default "In{n}" label. */
	inputName: string,
	inputMuted: boolean,
	outputMuted: boolean,
	/**
	 *  Trimmed, `_XXXX` hash suffix removed; empty when unnamed or still the
	 *  default "Out{letter}" label.
	 */
	outputNameBase: string,
	sourceTrims: SourceTrims,
	/**  Shown, never hashed — see the module doc comment. */
	backupPriority: BackupPriority,
};

export type ChannelConfig = {
	channelIndex: number,
	delayInMs: number | null,
	/**
	 *  Sourced from the trailer's `muteIn` block, NOT any channel-body byte
	 *  — see `channel_config_v118.rs`.
	 */
	inputMuted: boolean,
	matrixCrosspoints: MatrixCrosspoint[],
	inputEq: ChannelEq,
	outputEq: ChannelEq,
	outputTrimDb: number | null,
	outputVolumeDb: number | null,
	outputMuted: boolean,
	delayOutMs: number | null,
	outputPhaseInverted: boolean,
	noiseGateEnabled: boolean,
	limiter: Limiter,
	firBypassed: boolean,
	/**
	 *  `None` when the raw byte doesn't match a confirmed mapping — no
	 *  mapping table for this exists anywhere in this codebase yet, so an
	 *  unconfirmed guess is never substituted (see `channel_config_v118.rs`).
	 */
	powerMode: PowerMode | null,
	/**
	 *  `None` when the raw source-selector byte doesn't match a confirmed
	 *  mapping — same honesty rule as `power_mode`.
	 */
	source: ChannelSource | null,
	inputName: string | null,
	outputName: string | null,
	analogTrimDb: number | null,
	analogDelayMs: number | null,
	danteTrimDb: number | null,
	danteDelayMs: number | null,
	aes3TrimDb: number | null,
	aes3DelayMs: number | null,
	/**
	 *  Vendor `load_data` — the load impedance the amp is set to (Ω; unit to
	 *  verify on hardware).
	 */
	loadOhms: number | null,
	backupPriority: BackupPriority,
};

export type ChannelConfigSnapshot = {
	channels: ChannelConfig[],
	/**
	 *  Header `Standby` — whether the amp is in standby. True for both the
	 *  plain standby value and the locked-out one (see `standby_locked`);
	 *  `None` for a byte outside the known 0/1/2 set.
	 */
	standby: boolean | null,
	/**
	 *  Whether standby is locked out on the amp, i.e. it will ignore a
	 *  standby write. Comes from the same header byte as `standby` (the value
	 *  `2`), so it is `Some(false)` whenever `standby` is known and not
	 *  locked, and `None` exactly when `standby` is `None`. The frontend
	 *  disables its standby control on `Some(true)` rather than letting the
	 *  user press something the amp will drop.
	 */
	standbyLocked: boolean | null,
	/**
	 *  Header `Rotary_lock` (front-panel knob lock); `None` for a byte other
	 *  than 0/1.
	 */
	rotaryLocked: boolean | null,
	/**  Label of the last recalled preset (trailer `Scene_mode_name`). */
	presetName: string | null,
	receivedAt: number | null,
};

/**
 *  A full 10-band EQ chain (HP crossover + 8 parametric bands + LP
 *  crossover) for one channel, one direction. `AmpChannel` holds two of
 *  these (`input_eq`/`output_eq`) — Input/Output tabs' EQ sub-tabs.
 *  `bands.len()` == `AmpDspTopology.eq_bands_per_channel - 2`; grown/shrunk
 *  alongside `channels` whenever the assigned model's topology changes, see
 *  `reconcile_eq_bands`.
 */
export type ChannelEq = {
	hp: CrossoverSlot,
	bands: EqBand[],
	lp: CrossoverSlot,
};

export type ChannelFingerprint = {
	channelIndex: number,
	/**  Output letter, "A", "B", … */
	label: string,
	speakerHash: string | null,
	outputName: string | null,
	/**  `XXXX` from an output name ending in `_XXXX`, if present. */
	embeddedHash: string | null,
	/**  Set only when both `embedded_hash` and `speaker_hash` exist. */
	embeddedHashMatches: boolean | null,
	speaker: SpeakerCanonical,
	ampFields: ChannelAmpCanonical,
};

/**
 *  Which physical input feeds a channel — a `SourceKind` alone isn't enough
 *  to identify one, since a model typically exposes several physical inputs
 *  per kind (e.g. 4 analog inputs on a 4-channel amp); `index` picks which
 *  one (0.. the kind's `SourceChannelCount.channel_count`).
 */
export type ChannelSource = {
	kind: SourceKind,
	index: number,
};

export type CrossoverCanonical = {
	filterType: CrossoverFilterType,
	freqHz: number | null,
	active: boolean,
};

/**
 *  Numeric filter-type identifiers for the HP (band 0) / LP (band 9) crossover
 *  slots — ported 1:1 from the old app's `HPLP_FILTER_TYPE_NAMES`. Scaffolding
 *  only, same status as `EqFilterType`.
 */
export type CrossoverFilterType = "butterworth12" | "bessel12" | "linkwitzRiley12" | "butterworth18" | "butterworth24" | "bessel24" | "linkwitzRiley24" | "butterworth36" | "butterworth48" | "bessel48" | "linkwitzRiley48";

/**
 *  One HP or LP crossover slot (band 0 / band 9 of the fixed 10-band chain —
 *  see `EQ_BANDS_PER_CHANNEL`). No `q` field: Q is implied entirely by
 *  `filter_type` (e.g. "BW-12" always means Q=1/sqrt(2), never a
 *  user-settable independent value), confirmed against the old app's
 *  reference UI. Has `active` — HP/LP slots are independently bypassable.
 */
export type CrossoverSlot = {
	filterType: CrossoverFilterType,
	freqHz: number | null,
	active: boolean,
};

/**  Which crossover slot (band 0 or band 9) a command targets. */
export type CrossoverSlotKind = "hp" | "lp";

/**
 *  Partial update for a `CrossoverSlot` — same bundling rationale as
 *  `EqBandPatch`.
 */
export type CrossoverSlotPatch = {
	filterType: CrossoverFilterType | null,
	freqHz: number | null,
	active: boolean | null,
};

export type CrosspointCanonical = {
	sourceIndex: number,
	gainDb: number | null,
	active: boolean,
};

/**
 *  Numeric firmware "generation" (vNum) and the feature deltas it gates —
 *  ported from the old app's `lib/amp-version.ts`. Computed fresh from a
 *  firmware version string every time; never persisted independently.
 * 
 *  Deliberately has no trim/volume split flag: that file's comment claims a
 *  "split trim/volume" arrives at 119, but output Volume (FC=9 flag 0) and
 *  Trim (FC=9 flag 1) are both real, separate controls on 1.1.8 and 1.1.9
 *  alike — the old app's own dashboard always showed both.
 */
export type CvrFirmwareCapability = {
	vNum: number | null,
	extendedEq: boolean,
	phonicVariant: boolean,
	speakerManagement: boolean,
	firFilters: boolean,
	noiseGateThreshold: boolean,
	extendedDelay: boolean,
};

/**
 *  Event/command payload pairing a device id with its latest FC=59 preset
 *  snapshot — the shape `live_presets:updated` emits and
 *  `live_control_get_presets` returns a snapshot `Vec` of.
 *  Event/command payload pairing a device id with its latest FC=50 bridge
 *  snapshot — the shape `live_bridge:updated` emits and
 *  `live_control_get_bridge` returns a `Vec` of.
 */
export type DeviceBridge = {
	deviceId: string,
	bridge: DeviceBridgeSnapshot,
};

export type DeviceBridgeSnapshot = {
	/**
	 *  Indexed by pair — `bridged[0]` is outputs A/B, `bridged[1]` is C/D.
	 *  A pair the device has not answered for yet is `None` rather than
	 *  `false`, so "not reported" never renders as a confident "not
	 *  bridged".
	 */
	bridged: (boolean | null)[],
	receivedAt: number | null,
};

/**
 *  Event/command payload pairing a device id with its latest channel-config
 *  snapshot — the shape `live_channel_config:updated` emits and
 *  `live_control_get_channel_config` returns a snapshot `Vec` of.
 */
export type DeviceChannelConfig = {
	deviceId: string,
	config: ChannelConfigSnapshot,
};

/**
 *  Persists which catalog `AmpModelCatalogEntry` a live-discovered device
 *  (identified by MAC, not by any Project's `AmpAssignment`) should be
 *  configured as — needed so Direct Edit mode can resolve `AmpCapability`
 *  for a bare `DiscoveredDevice` the same way Project mode resolves it for
 *  an `AmpAssignment`. Deliberately independent of `AmpAssignment.mac`
 *  (which stays unpopulated) and of any `Project` — this is a small,
 *  standalone, MAC-keyed pairing, not the (separate, out-of-scope) feature
 *  of linking a live device into a Project's persisted config.
 */
export type DeviceModelLink = {
	mac: string,
	ampModelId: string,
	/**
	 *  `true` when produced by `match_catalog_model`, `false` when the user
	 *  explicitly picked/overrode it — an auto-match is safe to silently
	 *  re-run and refresh on every reconnect, a manual pick never is.
	 */
	autoMatched: boolean,
	updatedAt: number | null,
};

export type DevicePresets = {
	deviceId: string,
	presets: DevicePresetsSnapshot,
};

export type DevicePresetsSnapshot = {
	slots: PresetSlot[],
	activePresetName: string | null,
	receivedAt: number | null,
};

/**
 *  Event/command payload pairing a device id with its latest telemetry —
 *  the shape `live_telemetry:updated` emits and `live_control_get_telemetry`
 *  returns a snapshot `Vec` of.
 */
export type DeviceTelemetry = {
	deviceId: string,
	telemetry: Telemetry,
};

export type DiscoveredDevice = {
	/**  "{driver_id}:{mac}", e.g. "cvr:AA:BB:CC:DD:EE:FF" — stable, brand-namespaced. */
	id: string,
	driverId: string,
	brand: string,
	name: string,
	mac: string,
	ip: string,
	firmwareVersion: string,
	/**
	 *  Human-readable firmware family (e.g. "1.1.8"/"1.1.9" for CVR),
	 *  `None` if unknown or not applicable to this brand's protocol.
	 *  Brand-agnostic free text — driver-specific detection enums (like
	 *  CVR's `CvrFirmwareFamily`) map into this rather than leaking here.
	 */
	firmwareFamily: string | null,
	gainMax: number,
	analogInputChannels: number,
	digitalInputChannels: number,
	outputChannels: number,
	/**
	 *  Raw FC=0 BASIC_INFO `Machine_state` byte — the same vendor state enum
	 *  the heartbeat's per-channel bytes use. Kept raw for wire debugging;
	 *  `machine_state_decoded` is the form the UI reads.
	 */
	machineState: number,
	/**
	 *  `machine_state` decoded. `None` for a firmware family with no state
	 *  table (see `cvr::channel_state::decode`) — never a guessed meaning.
	 */
	machineStateDecoded: AmpChannelState | null,
	online: boolean,
	lastSeenAt: number | null,
};

/**
 *  Marks whether a catalog entry (Amp Model Catalog) was
 *  authored by the user or shipped built-in with the app.
 */
export type EntryOrigin = "userDefined" | "builtIn";

/**
 *  One of the 8 parametric bands (bands 1-8 of the fixed 10-band chain).
 *  `active` mirrors `MatrixCrosspoint.active` — lets a band be fully
 *  disengaged independent of its stored gain/freq/Q.
 */
export type EqBand = {
	filterType: EqFilterType,
	freqHz: number | null,
	gainDb: number | null,
	q: number | null,
	active: boolean,
};

export type EqBandCanonical = {
	filterType: EqFilterType,
	freqHz: number | null,
	/**  `None` when the filter type has no gain. */
	gainDb: number | null,
	/**  `None` when the filter type has no Q. */
	q: number | null,
	active: boolean,
};

/**
 *  Partial update for one `EqBand` — bundled into a single struct param
 *  (rather than 5 separate `Option<T>` params) because `projects_set_eq_band`
 *  otherwise exceeds `tauri-specta`'s `SpectaFn` 10-parameter limit. Every
 *  field `None` means "leave unchanged", same semantics as the flat
 *  `Option<T>` params every other partial-update command uses.
 */
export type EqBandPatch = {
	filterType: EqFilterType | null,
	freqHz: number | null,
	gainDb: number | null,
	q: number | null,
	active: boolean | null,
};

export type EqCanonical = {
	hp: CrossoverCanonical,
	bands: EqBandCanonical[],
	lp: CrossoverCanonical,
};

/**  Which of a channel's two independent 10-band EQ chains a command targets. */
export type EqDirection = "input" | "output";

/**
 *  One `EqFilterType` variant's resolved capabilities — pairs the type with
 *  its `FilterCapabilities` so the frontend can gate a band's gain/Q inputs
 *  from `AmpCapability.eq_filter_capabilities` instead of hardcoding a copy
 *  of `EqFilterType::capabilities()`'s table in TypeScript. Keeps this
 *  genuinely capability-driven: if a future model or firmware ever needs a
 *  *different* gain/Q table, `eq_filter_capabilities()` is the one place
 *  that changes — no frontend edit required, same as `paramRanges`/
 *  `topology`/firmware flags.
 */
export type EqFilterCapabilityEntry = {
	filterType: EqFilterType,
	supportsGain: boolean,
	supportsQ: boolean,
};

/**
 *  Numeric filter-type identifiers for the 8 parametric EQ bands (bands 1-8 of
 *  the fixed 10-band-per-direction structure) — ported 1:1 from the old app's
 *  `EQ_FILTER_TYPE_NAMES`/`getEqFilterTypeCapabilities`. Scaffolding only: not
 *  yet consumed by any UI or persisted field this phase.
 */
export type EqFilterType = "peaking" | "lowShelf" | "highShelf" | "allPass1st" | "allPass2nd" | "generalLow" | "generalHigh" | "butterworthLow" | "butterworthHigh" | "besselLow" | "besselHigh";

/**
 *  Where a fingerprint came from. Flat rather than an internally tagged enum:
 *  `kind` says which of the optional ids are set.
 */
export type FingerprintOrigin = {
	kind: FingerprintSource,
	projectId: string | null,
	assignmentId: string | null,
	deviceId: string | null,
	mac: string | null,
	label: string | null,
};

/**
 *  One compared setting of two fingerprints. Values are formatted at exactly
 *  the precision the hash encodes, and a value the hash skips (bypassed band,
 *  disabled limiter, inactive crosspoint, unused gain/Q) is shown as
 *  "bypassed"/"off" — so two rows are equal exactly when they hash equal, and
 *  the red highlights can never disagree with the lock.
 */
export type FingerprintRow = {
	/**  "Amp", "In 1", "Out A", … */
	group: string,
	label: string,
	/**
	 *  `None` when this side has no such setting (e.g. a channel the other
	 *  side lacks).
	 */
	project: string | null,
	live: string | null,
	differs: boolean,
	/**
	 *  `false` for status rows (standby, preset name, knob lock) and for
	 *  backup priority (unverified — see the module doc comment): shown for
	 *  context, never compared.
	 */
	hashed: boolean,
};

export type FingerprintSource = "offline" | "online";

/**
 *  A channel's output protection: independent RMS and Peak limiter stages,
 *  ported from the old app's `limiter-panel.tsx` (both stages can be engaged
 *  simultaneously, each with its own enable flag).
 */
export type Limiter = {
	rms: RmsLimiter,
	peak: PeakLimiter,
};

/**
 *  Partial update for a `Limiter` — bundled into a single struct param for
 *  the same `SpectaFn` 10-parameter reason as `EqBandPatch`/`CrossoverSlotPatch`.
 */
export type LimiterPatch = {
	rmsEnabled: boolean | null,
	rmsThresholdVrms: number | null,
	rmsAttackMs: number | null,
	rmsReleaseMultiplier: number | null,
	peakEnabled: boolean | null,
	peakThresholdVp: number | null,
	peakHoldMs: number | null,
	peakReleaseMs: number | null,
};

/**
 *  What a live write reports back so the frontend can confirm delivery in the
 *  UI, not just in the console. Aggregated across every packet one command
 *  puts on the wire — an EQ band patch is up to 4, a crossover slot up to 3.
 */
export type LiveWriteAck = {
	/**  Packets this command produced, coalesced ones included. */
	packets: number,
	/**
	 *  Highest transmission count any one packet needed. 1 means everything
	 *  was acknowledged on its first send; higher means refires were spent.
	 */
	attempts: number,
	/**  Summed ACK round-trip over the packets that actually went out. */
	elapsedMs: number,
	/**
	 *  Packets superseded by a newer write to the same parameter before they
	 *  were ever transmitted (see `WriteOutcome::attempts == 0`). A command
	 *  whose packets were *all* coalesced did nothing on the wire, and the
	 *  UI should stay quiet about it — the write that replaced it reports.
	 */
	coalesced: number,
};

/**
 *  One crosspoint in a channel's row of the input matrix — the gain/active
 *  state for a single source position. `source_index` is positional (0..
 *  `AmpDspTopology.matrix_input_count`), not a `SourceKind` itself, since a
 *  model can have multiple sources of the same kind (e.g. 4 analog + 4 Dante
 *  inputs on a Dante-equipped model).
 */
export type MatrixCrosspoint = {
	sourceIndex: number,
	gainDb: number | null,
	active: boolean,
};

/**  An inclusive min/max bound for a numeric parameter. */
export type ParamRange = {
	min: number | null,
	max: number | null,
};

/**  Instantaneous peak limiter stage — ranged by `AmpParamRanges.peak_limiter_*`. */
export type PeakLimiter = {
	enabled: boolean,
	thresholdVp: number | null,
	holdMs: number | null,
	releaseMs: number | null,
	/**  Vendor `peak_Limiter_max` (V). Read back, not yet editable here. */
	maxVp?: number | null,
};

export type PeakLimiterCanonical = {
	enabled: boolean,
	thresholdVp: number | null,
	holdMs: number | null,
	releaseMs: number | null,
	maxVp: number | null,
};

/**  Output power/impedance mode — ported from the old app's `POWER_MODE_NAMES`. */
export type PowerMode = "lowOhm" | "v70" | "v100";

export type PresetSlot = {
	index: number,
	name: string,
};

export type Project = {
	id: string,
	name: string,
	description: string,
	schemaVersion: number,
	createdAt: number | null,
	updatedAt: number | null,
	ampAssignments: AmpAssignment[],
};

/**  RMS-window limiter stage — ranged by `AmpParamRanges.rms_limiter_*`. */
export type RmsLimiter = {
	enabled: boolean,
	thresholdVrms: number | null,
	attackMs: number | null,
	releaseMultiplier: number | null,
	/**  Vendor `RMS_Limiter_Auto`. Read back, not yet editable here. */
	auto?: boolean,
	/**  Vendor `RMS_Limiter_max` (V). Read back, not yet editable here. */
	maxVrms?: number | null,
};

export type RmsLimiterCanonical = {
	enabled: boolean,
	thresholdVrms: number | null,
	attackMs: number | null,
	releaseMultiplier: number | null,
	auto: boolean,
	maxVrms: number | null,
};

/**
 *  How many physical channels of one `SourceKind` a model exposes, and
 *  whether any of them can feed any digital input (`patchable`) or each one
 *  is hard-wired to the matching digital input only. Analog is patchable —
 *  e.g. a 4-channel amp's Analog-3 jack can feed digital input 1. Dante is
 *  not: Dante channel N only ever feeds digital input N (Dante routing
 *  happens upstream, at the network/Dante Controller level, not on this
 *  amp's input matrix), so digital input N's only Dante option is "Dante-N".
 */
export type SourceChannelCount = {
	kind: SourceKind,
	channelCount: number,
	/**
	 *  `#[serde(default)]` so `sourceCounts` entries saved before this field
	 *  existed still deserialize (as `false`) instead of hard-failing store
	 *  load entirely — `migrate_builtin_topology` immediately recomputes the
	 *  real value for `BuiltIn` entries on the very next load either way.
	 */
	patchable?: boolean,
};

/**
 *  Which physical input can feed a channel — the generic, protocol-agnostic
 *  source vocabulary. Which variants a given model actually offers, and how
 *  many physical channels each variant has, is `AmpDspTopology.source_counts`,
 *  not this enum itself.
 */
export type SourceKind = "analog" | "dante" | "aes3" | "backup";

/**  One trim + delay pair for a single input source kind. */
export type SourceTrim = {
	trimDb: number | null,
	delayMs: number | null,
};

/**
 *  Per-source gain matching (vendor `Ana/Dante/AES_gain_matching`) — each
 *  source kind feeding a channel has its own trim and delay.
 */
export type SourceTrims = {
	analog: SourceTrim,
	dante: SourceTrim,
	aes3: SourceTrim,
};

/**  The values `speakerHash` is computed from. */
export type SpeakerCanonical = {
	outputEq: EqCanonical,
	rmsLimiter: RmsLimiterCanonical,
	peakLimiter: PeakLimiterCanonical,
	delayOutMs: number | null,
	phaseInverted: boolean,
	/**  `None` only for a live channel whose power-mode byte is unmapped. */
	powerMode: PowerMode | null,
	loadOhms: number | null,
	firBypassed: boolean,
};

export type Telemetry = {
	/**  5 readings: [0-3] = per-channel, [4] = PSU. */
	temperatures: (number | null)[],
	outputVoltages: (number | null)[],
	outputCurrents: (number | null)[],
	outputImpedance: (number | null)[],
	/**
	 *  dB relative to the device's rated RMS output voltage (`0dB` = rated
	 *  max output) — `None` per-channel until `driver.rs` fills it in, since
	 *  the wire-format adapters (`telemetry_v118`/`telemetry_v119`) only see
	 *  raw packet bytes, not the device's firmware-version string needed to
	 *  look up a real reference voltage (see
	 *  `capability::cvr::rated_rms_voltage_from_firmware_string`). Stays
	 *  `None` entirely for a model this app doesn't recognize — never a
	 *  guessed/default reference.
	 */
	outputLevelDb: (number | null)[],
	/**
	 *  The real reference voltage `output_level_db` was computed against
	 *  (`0dB` = this voltage) — device-wide, not per-channel. Exposed
	 *  alongside `output_level_db` so the frontend can scale a meter against
	 *  the *real* rated voltage instead of an approximate/generic constant.
	 *  `None` under the same conditions as `output_level_db`.
	 */
	ratedRmsVoltage: number | null,
	/**
	 *  Raw per-output state bytes, straight off the wire — kept alongside the
	 *  decoded `output_channel_states` for wire debugging and because the
	 *  decode needs a firmware family this adapter never sees.
	 */
	outputStates: number[],
	inputVoltages: (number | null)[],
	inputDbfs: (number | null)[],
	limiters: (number | null)[],
	/**
	 *  Raw per-input `InStates` bytes — signed, as the vendor struct declares
	 *  them. NOT the same enum as `output_states`: see `input_clipping`.
	 *  Empty on the body lengths that don't carry the field at all.
	 */
	inputStates: number[],
	/**
	 *  `output_states` decoded to meanings, one entry per raw entry so a
	 *  short packet stays distinguishable from a full one. Every element is
	 *  `None` until `driver.rs` fills it in (and stays `None` for a firmware
	 *  family with no state table), for the same reason `output_level_db`
	 *  does: the wire adapters only see raw bytes, never the device's
	 *  firmware family.
	 */
	outputChannelStates: (AmpChannelState | null)[],
	/**
	 *  Per-input clip flag, decoded from `input_states`. The vendor's
	 *  heartbeat struct calls this field `InStates: sbyte[4]` and gives it its
	 *  own two-value enum, `Struct_test.InputChState { Clip = 0, None = 1 }` —
	 *  it is emphatically *not* the 12-value `Jiqizhuangtai` the output states
	 *  use, so there is no such thing as a per-input operating state.
	 * 
	 *  The two references disagree on what the byte means and both can't be
	 *  right: the vendor enum names `0` "Clip" and the vendor UI lights a
	 *  yellow LED when it reads 0, while the prior web implementation reads
	 *  the same `0` as "signal present" and shows green. This follows the
	 *  vendor. `input_states` stays exposed raw so a check against real
	 *  hardware can settle it without a rebuild.
	 * 
	 *  Element is `None` for a byte outside the known 0/1 set; the whole vec
	 *  is empty when the packet doesn't carry the field.
	 */
	inputClipping: (boolean | null)[],
	/**
	 *  `machine_mode` decoded to a meaning — the amp-level state, and what the
	 *  reference web app drives its standby indicator from. Same fill-in and
	 *  `None` rules as `output_channel_states`.
	 */
	machineStateDecoded: AmpChannelState | null,
	/**
	 *  `None` on the (common) heartbeat body lengths that don't include this
	 *  trailing field at all — only the 96-byte `WHOLE118_PLUS` variant
	 *  carries it. Was previously a bare `f32` that silently defaulted to
	 *  `0.0` on every shorter body, i.e. real-looking fake data for any
	 *  device that isn't actually sending the 96-byte variant.
	 */
	fanVoltage: number | null,
	machineMode: number,
	receivedAt: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

